#pragma once

// common application definitions
#define			APPNAME							L"LGTV Companion"
#define         APP_VERSION                     L"5.0.2"
#define			CONFIG_FILE						L"config.json"
#define			LOG_FILE						L"log.txt"
#define			WINDOW_CLASS_UNIQUE				L"YOLOx0x0x0181818"
#define         PIPENAME                        TEXT("\\\\.\\pipe\\LGTVyolo")
#define         NEWRELEASELINK                  L"https://github.com/JPersson77/LGTVCompanion/releases"
#define         VERSIONCHECKLINK                L"https://api.github.com/repos/JPersson77/LGTVCompanion/releases/latest"
#define         DONATELINK                      L"https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=jorgen.persson@gmail.com&lc=US&item_name=Friendly+gift+for+the+development+of+LGTV+Companion&no_note=0&cn=&currency_code=EUR&bn=PP-DonationsBF:btn_donateCC_LG.gif:NonHosted"
#define         DISCORDLINK                     L"https://discord.gg/7KkTPrP3fq"
#define			RESTARTWORDSLINK				L"https://docs.google.com/spreadsheets/d/1SNjYh7kt4aVhHg0ZjI3i96vCeOJZJS73o9Wl-OVEvzk/edit#gid=0"
#define			TASK_FOLDER						L"\\LGTV Companion"
#define			TASK_UPDATER_SILENT				L"LGTVC Silent Update Task"
#define			TASK_DAEMON						L"LGTVC Run Daemon Task"
#define			TASK_DAEMON_VISIBLE				L"LGTVC Run Daemon Visible Task"
#define			CUSTOM_MESSAGE_RESTART			L"LGTVC_CUSTOM_MESSAGE_RESTART"
#define			CUSTOM_MESSAGE_CLOSE			L"LGTVC_CUSTOM_MESSAGE_CLOSE"
#define			CUSTOM_MESSAGE_IDLE				L"LGTVC_CUSTOM_MESSAGE_IDLE"
#define			CUSTOM_MESSAGE_UNIDLE			L"LGTVC_CUSTOM_MESSAGE_UNIDLE"
#define			CUSTOM_MESSAGE_UPD_FOCUS		L"LGTVC_CUSTOM_MESSAGE_UPD_FOCUS"
#define			CUSTOM_MESSAGE_UPD_REFRESH		L"LGTVC_CUSTOM_MESSAGE_UPD_REFRESH"
#define			CUSTOM_MESSAGE_UPD_CLOSE		L"LGTVC_CUSTOM_MESSAGE_UPD_CLOSE"
#define			CUSTOM_MESSAGE_LGTVC_CLOSE		L"LGTVC_CUSTOM_MESSAGE_LGTVC_CLOSE"