R"(
{
  "Restart" : [
    "restart",
    "redémarrer",
    "starta om",
    "reiniciar",
    "reinicio",
    "重启",
    "重新啟動",
    "yeniden başlat",
    "Yeniden Başlat",
    "Перезагрузка",
    "uruchomienie ponowne",
    "다시 시작",
    "Riavvia",
    "Riavviare",
    "Riavvio",
    "riavvia",
    "riavviare",
    "riavvio",
    "Restartování",
    "restartování",
    "neu starten",
    "Opnieuw opstarten",
    "opnieuw opstarten",
    "uudelleenkäynnistys",
    "Перезавантажити",
    "ponovno pokretanje",
    "repornire",
    "repornit",
    "ujrainditas",
    "újrakezd",
    "újraindítás",
    "Genstart",
    "genstart"
  ],
  "Shutdown" : [
    "shutdown",
    "power off",
    "arrêter",
    "se mettre hors tension",
    "se mettre hors tension.",
    "stäng av",
    "apagar",
    "apagado",
    "Apagar el sistema",
    "apagar el sistema",
    "关机",
    "关闭电源",
    "電源關閉",
    "關機",
    "kapat",
    "Kapat",
    "Завершение работы",
    "wyłączenie zasilania",
    "zamknięcie",
    "전원 끄기",
    "종료",
    "Arresta il sistema",
    "Spegni",
    "Spegnimento",
    "Spegnere",
    "arresta il sistema",
    "spegni",
    "spegnimento",
    "spegnere",
    "Desligado",
    "Desligar o sistema",
    "desligado",
    "desligar o sistema",
    "Vypnout",
    "vypnout",
    "Napájení vypnuto",
    "napájení vypnuto",
    "Ausschalten",
    "ausschalten",
    "Herunterfahren",
    "herunterfahren",
    "Afsluiten",
    "afsluiten",
    "virrankatkaisu",
    "sammuta",
    "Завершити роботу",
    "isključivanje",
    "isključivanje napajanja",
    "oprire",
    "inchide",
    "leallitas",
    "Leállitás"
  ]
}
)"