//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LGTV Companion UI.rc
//
#define IDC_MYICON                      2
#define IDCONFIGURE                     3
#define IDD_LGTVCOMPANIONUI_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        129
#define IDR_BUTTONMENU                  130
#define IDD_DEVICE                      131
#define IDD_OPTIONS                     132
#define IDD_DEVICE1                     133
#define IDD_WAIT                        133
#define IDI_ICON1                       142
#define IDI_ICON2                       143
#define IDD_CONFIGURE_TOPOLOGY          144
#define IDI_ICON4                       149
#define IDI_ICON3                       150
#define IDD_ADVANCEDIDLE                153
#define IDD_WHITELIST_EDIT              154
#define IDC_COMBO                       1000
#define IDC_SPLIT                       1001
#define IDC_OPTIONS                     1002
#define IDC_CHECK_ENABLE                1003
#define IDC_CHECK_POWERAUTO             1004
#define IDC_CHECK_AWAYAUTO              1005
#define IDC_DEVICEIP                    1005
#define IDC_DEVICEMACS                  1006
#define IDC_DEVICENAME                  1007
#define IDC_DEVICEIP2                   1008
#define IDC_SUBNET                      1008
#define IDC_SPIN                        1009
#define IDC_TIMEOUT                     1010
#define IDC_LOGGING                     1011
#define IDC_AUTOUPDATE                  1012
#define IDC_CHECK_BLANK                 1013
#define IDC_SYSLINK                     1014
#define IDC_EDIT_BLANK                  1015
#define IDC_SPIN2                       1016
#define IDC_CHECK_RDPBLANK              1017
#define IDC_CHECK_REMOTE                1017
#define IDC_LIST                        1018
#define IDC_SYSLINK3                    1019
#define IDC_LIST2                       1019
#define IDC_SYSLINK5                    1020
#define IDC_NEWVERSION                  1021
#define IDC_SYSLINK2                    1021
#define IDC_RADIO1                      1022
#define IDC_DONATE                      1022
#define IDC_SYSLINK6                    1022
#define IDC_RADIO2                      1023
#define IDC_SYSLINK7                    1023
#define IDC_RADIO3                      1024
#define IDC_SYSLINK4                    1025
#define IDC_SYSLINK11                   1025
#define IDC_HDMI_INPUT_NUMBER_CHECKBOX  1026
#define IDC_HDMI_INPUT_NUMBER           1027
#define IDC_HDMI_INPUT_NUMBER_SPIN      1028
#define IDC_SET_HDMI_INPUT_CHECKBOX     1029
#define IDC_TEST                        1029
#define IDC_SET_HDMI_INPUT_NUMBER       1030
#define IDC_CHECK_TOPOLOGY              1030
#define IDC_SET_HDMI_INPUT_SPIN         1031
#define IDC_GO                          1031
#define IDC_STATIC_NO_1                 1032
#define IDC_SYSLINK8                    1032
#define IDC_STATIC_NO_2                 1033
#define IDC_SYSLINK9                    1033
#define IDC_STATIC_NO_3                 1034
#define IDC_SYSLINK10                   1034
#define IDC_STATIC_NO_4                 1035
#define IDC_STATIC_T_1                  1036
#define IDC_STATIC_T_11                 1036
#define IDC_STATIC_T_2                  1037
#define IDC_STATIC_T_12                 1037
#define IDC_STATIC_T_3                  1038
#define IDC_STATIC_T_14                 1038
#define IDC_STATIC_T_4                  1039
#define IDC_STATIC_T_16                 1039
#define IDC_STATIC_STATUS_1             1040
#define IDC_STATIC_STATUS_2             1041
#define IDC_STATIC_C                    1042
#define IDC_STATIC_T_5                  1042
#define IDC_STATIC_T_15                 1042
#define IDC_STATIC_NO_6                 1043
#define IDC_STATIC_T_13                 1044
#define IDC_SYSLINK_CONF                1044
#define IDC_GO2                         1045
#define IDC_SYSLINK_CONF2               1045
#define IDC_CHECK_FULLSCREEN            1045
#define IDC_STATIC_NO_5                 1046
#define IDC_EDIT_TIME                   1046
#define IDC_CHECK_WHITELIST             1049
#define IDC_CHECK_FS_EXCLUSIONS         1050
#define IDC_SYSLINK_ADD                 1055
#define IDC_SYSLINK_DELETE              1056
#define IDC_SYSLINK_EDIR                1057
#define IDC_EDIT_NAME                   1057
#define IDC_SYSLINK_INFO_2              1058
#define IDC_EDIT_PROCESS                1058
#define IDC_SYSLINK_INFO_3              1059
#define IDC_SYSLINK_BROWSE              1059
#define IDC_SYSLINK_INFO_1              1060
#define IDC_COMBO_MODE                  1061
#define IDC_SYSLINK_ADD2                1061
#define IDC_SYSLINK_EDIR2               1062
#define IDC_COMBO_SSL                   1063
#define IDC_SYSLINK_DELETE2             1063
#define IDC_CHECK_API                   1064
#define IDC_CHECK1                      1066
#define IDC_CHECK_MUTE                  1066
#define IDC_COMBO1                      1067
#define IDC_COMBO_TIMING                1067
#define ID_ADD_MANAGE                   32771
#define ID_ADD_MANAGE32772              32772
#define ID_ADD_REMOVE                   32773
#define ID_ADD_SCAN                     32774
#define ID_ADD_TEST                     32775
#define ID_ADD_TURNON                   32776
#define ID_ADD_TURNOFF                  32777
#define ID_M_MANAGE                     32778
#define ID_M_REMOVE                     32779
#define ID_M_ADD                        32780
#define ID_M_TEST                       32781
#define ID_M_TURNON                     32782
#define ID_M_TURNOFF                    32783
#define ID_M_SCAN                       32784
#define ID__REMOVEALL                   32785
#define ID__M_REMOVEALL                 32786
#define ID_M_REMOVEALL                  32787
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32788
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
